package com.example.narumanam

data class OrderManageProduct (
    val orderId: String = "",
    val globProductId: String = "",
    val buyerPhoneNumber: String = "",
    val sellerPhoneNumber: String = "",
    val sellerName: String = "",
    val orderedQuantity: String = "",
    val quantityCategory: String = "",
    val productCategory: String = "",
    val productName: String = "",
    val productImage: String = "",
    val courierPartnerName: String = "",
    val courierTrackId: String = "",
    val price: String = "",
    val orderedDate: String = "",
    val orderedTime: String = "",
    val shippedDate: String = "",
    val shippedTime: String = "",
    val cancelDate: String = "",
    val addressId: String= "",
    val phoneNumber: String = "",
    val userName: String = "",
    val customerName: String = "",
    val houseNo: String = "",
    val streetName: String = "",
    val nearestLandMark: String = "",
    val pinCode: String = "",
    val district: String = "",
    val state: String = "",
    val orderStatus: String = "",
    val orderProgressing: String = "",
    )